services:
  myweb-dev:
    image: nginx:latest
    container_name: myweb-dev
    ports:
      - "1000:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - myapp-net
 

networks:
  myapp-net:
    driver: bridge